version: "3.7"

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn server.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      DB_CLIENT: mongodb://root:root@db:27017
    networks:
      - webnet
    depends_on:
      - db
    

  db:
    image: mongo:3.6
    volumes:
      - mongo_data:/var/lib/mongo/data/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - webnet
    expose:
      - 27017

networks:
  webnet:

volumes:
  mongo_data:
